# Generated by Django 5.1.3 on 2025-02-12 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_swap_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=100)),
                ('solana', models.CharField(max_length=100)),
                ('usdt', models.CharField(max_length=100)),
                ('ethereum', models.CharField(max_length=100)),
                ('bnb', models.CharField(max_length=100)),
                ('xrp', models.CharField(max_length=100)),
                ('cardano', models.CharField(max_length=100)),
                ('dogecoin', models.CharField(max_length=100)),
                ('litecoin', models.CharField(max_length=100)),
                ('usdc', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
