# Generated by Django 5.1.3 on 2025-01-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_rename_wallet_address_deposit_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='confirm_payment',
        ),
    ]
