# Generated by Django 5.1.3 on 2025-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_remove_deposit_confirm_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED'), ('UNDERREVIEW', 'UNDERREVIEW')], default='UNDERREVIEW', max_length=50),
        ),
    ]
