# Generated by Django 5.1.3 on 2025-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bitcoin',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bnb',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cardano',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='dogecoin',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ethereum',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='litecoin',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='solana',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usdc',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usdt',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='xrp',
            field=models.IntegerField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MyAsset',
        ),
    ]
