# Generated by Django 5.1.3 on 2025-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_asset_bitcoin_alter_asset_bnb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED'), ('UNDERREVIEW', 'UNDERREVIEW'), ('PAID', 'PAID')], default='UNDERREVIEW', max_length=50),
        ),
    ]
