# Generated by Django 5.1.3 on 2025-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
