# Generated by Django 5.1.3 on 2025-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED'), ('PAID', 'PAID')], default='PENDING', max_length=50),
        ),
    ]
