# Generated by Django 5.1.3 on 2025-01-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='trading_platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
