# Generated by Django 5.1.3 on 2025-01-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_remove_dashboard_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='histotry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myasset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Histotry',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='myAsset',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
